$victoire = ($result->teamHome == $this->team) ? (($result->teamHomeScore > $result->teamVisitorScore) ? 'V' : 'D' ) : (($result->teamHomeScore > $result->teamVisitorScore) ? 'D' : 'V' );            $poss = ($result->twoT + $result->threeT) + (0.44 * $result->lt) + $result->bp - $result->ro;            $poss_op = ($result->twoT_op + $result->threeT_op) + 0.44 * $result->lt_op + $result->bp_op - $result->ro_op;            $pointEquipe = ($result->teamHome == $this->team) ? $result->teamHomeScore : $result->teamVisitorScore;
            $pointEquipeOpp = ($result->teamHome != $this->team) ? $result->teamHomeScore : $result->teamVisitorScore;            $ScPoss = ($result->twoR + $result->threeR)+(1-(1-($result->lt > 0 ? $result->lr / $result->lt : 0))^2)*$result->lt*0.4;
            $ScPoss_op = ($result->twoR_op + $result->threeR_op)+(1-(1-($result->lt_op > 0 ? $result->lr_op / $result->lt_op : 0))^2)*$result->lt_op*0.4;            $return = [
                $result->championship,
                $result->saeason,
                $result->gameDate,
                $result->gameDay,
                ($result->teamHome == $this->team) ? $result->teamHome : $result->teamVisitor,
                ($result->teamHome != $this->team) ? $result->teamHome : $result->teamVisitor,
                ($result->teamHome == $this->team) ? 'D' : 'E',
                $victoire,
                ($victoire == 'V') ? '1' : '0',
                $pointEquipe,
                $pointEquipeOpp,
                ($result->teamHome == $this->team) ? $result->teamHomeScore - $result->teamVisitorScore : $result->teamVisitorScore - $result->teamHomeScore,
                $result->minutes,                // Team Sélectionnée
                $result->twoR + $result->threeR,
                $result->twoT + $result->threeT,
                ($result->twoT + $result->threeT) > 0 ? round((($result->twoR + $result->threeR) * 100) / ($result->twoT + $result->threeT)) . '%' : '0%',
                $result->twoR,
                $result->twoT,
                $result->twoT > 0 ? round(($result->twoR * 100) / $result->twoT) . '%' : '0%',
                $result->threeR,
                $result->threeT,
                $result->threeT > 0 ? round(($result->threeR * 100) / $result->threeT) . '%' : '0%',
                $result->lr,
                $result->lt,
                $result->lt > 0 ? round(($result->lr * 100) / $result->lt) . '%' : '0%',
                $result->ro,
                $result->rd,
                $result->rt,
                $result->ct,
                $result->cs,
                $result->pd,
                $result->in,
                $result->bp,
                $result->fte,
                $result->fpr,
                $result->eval,                // Team adverse
                $result->twoR_op + $result->threeR_op,
                $result->twoT_op + $result->threeT_op,
                ($result->twoT_op + $result->threeT_op) > 0 ? round((($result->twoR_op + $result->threeR_op) * 100) / ($result->twoT_op + $result->threeT_op)) . '%' : '0%',
                $result->twoR_op,
                $result->twoT_op,
                $result->twoT_op > 0 ? round(($result->twoR_op * 100) / $result->twoT_op) . '%' : '0%',
                $result->threeR_op,
                $result->threeT_op,
                $result->threeT_op > 0 ? round(($result->threeR_op * 100) / $result->threeT_op) . '%' : '0%',
                $result->lr_op,
                $result->lt_op,
                $result->lt_op > 0 ? round(($result->lr_op * 100) / $result->lt_op) . '%' : '0%',
                $result->ro_op,
                $result->rd_op,
                $result->rt_op,
                $result->ct_op,
                $result->cs_op,
                $result->pd_op,
                $result->in_op,
                $result->bp_op,
                $result->fte_op,
                $result->fpr_op,
                $result->eval_op,                // Stats
                $poss,
                $poss_op,
                $poss > 0 ? round(100 * $pointEquipe / $poss, 1) : 0,
                $poss_op > 0 ? round(100 * $pointEquipeOpp / $poss_op, 1) : 0,
                ($poss > 0 ? round(100 * $pointEquipe / $poss, 1) : 0) - ($poss_op > 0 ? round(100 * $pointEquipeOpp / $poss_op, 1) : 0),
                ($result->twoT + $result->threeT) > 0 ? round(((($result->twoR + $result->threeR)+0.5*$result->threeR)/($result->twoT + $result->threeT)) * 100) . '%' : 0,
                ($result->ro+$result->rd_op) > 0 ? round(($result->ro/($result->ro+$result->rd_op))*100) . '%' : 0,
                $poss > 0 ? round(($result->in/$poss)*100) . '%' : 0,
                ($result->twoT + $result->threeT) > 0 ? round($result->lt/($result->twoT + $result->threeT),2) : 0,
                ($result->twoT_op + $result->threeT_op) > 0 ? round(((($result->twoR_op + $result->threeR_op)+0.5*$result->threeR_op)/($result->twoT_op + $result->threeT_op))*100) . '%' : 0,
                ($result->ro_op+$result->rd) > 0 ? round(( $result->ro_op/($result->ro_op+$result->rd))*100) . '%' : 0,
                $poss_op > 0 ? round(($result->in_op/$poss_op)*100) . '%' : 0,
                $result->twoT_op > 0 ? round($result->lt_op / $result->twoT_op + $result->threeT_op,2) : 0,
                $poss > 0 ? round(($ScPoss/$poss)*100) . '%' : 0,
                $poss_op > 0 ? round((($poss_op-$ScPoss_op)/$poss_op)*100) . '%' : 0,
                $poss > 0 ? round(($result->pd/$poss)*100) . '%' : 0,
                $poss_op > 0 ? round(($result->in/$poss_op)*100) . '%' : 0,
                $result->twoT_op > 0 ? round(($result->ct_op/$result->twoT_op)*100) . '%' : 0,
                $poss_op > 0 ? round(($result->pd_op/$poss_op)*100) . '%' : 0,
                $poss > 0 ? round(($result->in_op/$poss)*100) . '%' : 0,
                $result->twoT > 0 ? round(($result->ct_op/$result->twoT)*100) . '%' : 0,
                ($result->rd+$result->ro_op) > 0 ? round(($result->rd/($result->rd+$result->ro_op))*100) . '%' : 0,
                ($result->rt+$result->rt_op) > 0 ? round(($result->rt/($result->rt+$result->rt_op))*100) . '%' : 0,
                ($result->twoT_op + $result->threeT_op) > 0 ? round((($result->twoR_op + $result->threeR_op)/($result->twoT_op + $result->threeT_op))*100) . '%' : 0,
                $result->twoT_op > 0 ? round(($result->twoR_op/$result->twoT_op)*100) . '%' : 0,
                $result->threeT_op > 0 ? round(($result->threeR_op/$result->threeT_op)*100) . '%' : 0,
                ($result->twoT + $result->threeT) > 0 ? round(($result->twoT/($result->twoT + $result->threeT))*100) . '%' : 0,
                ($result->twoT + $result->threeT) > 0 ? round(($result->threeT/($result->twoT + $result->threeT))*100) . '%' : 0,
                ($result->twoT_op + $result->threeT_op) > 0 ? round(($result->twoT_op/($result->twoT_op + $result->threeT_op))*100) . '%' : 0,
                ($result->twoT_op + $result->threeT_op) > 0 ? round(($result->threeT_op/($result->twoT_op + $result->threeT_op))*100) . '%' : 0,
                round((((($result->twoT + $result->threeT) > 0 ? (($result->twoR + $result->threeR) / ($result->twoT + $result->threeT)) : 0) - (($result->twoT_op + $result->threeT_op) > 0 ? (($result->twoR_op + $result->threeR_op) / ($result->twoT_op + $result->threeT_op)) : 0) )*5+0.5)*100) . '%'
            ];
