                minutes,                // Team Sélectionnée
                twoR + threeR,
                twoT + threeT,
                (twoT + threeT) > 0 ? round(((twoR + threeR) * 100) / (twoT + threeT)) . '%' : '0%',
                twoR,
                twoT,
// TMFG2P%                <!-- twoT > 0 ? round((twoR * 100) / twoT) . '%' : '0%', -->
                threeR,
                threeT,
// TMFG3P%               <!-- threeT > 0 ? round((threeR * 100) / threeT) . '%' : '0%', -->
                lr,
                lt,
<!-- // TMFT%                lt > 0 ? round((lr * 100) / lt) . '%' : '0%', -->
                ro,
                rd,
                rt,
                ct,
                cs,
                pd,
                in,
                bp,
                fte,
                fpr,
                eval,                // Team adverse
                twoR_op + threeR_op,
                twoT_op + threeT_op,
                (twoT_op + threeT_op) > 0 ? round(((twoR_op + threeR_op) * 100) / (twoT_op + threeT_op)) . '%' : '0%',
                twoR_op,
                twoT_op,
                twoT_op > 0 ? round((twoR_op * 100) / twoT_op) . '%' : '0%',
                threeR_op,
                threeT_op,
                threeT_op > 0 ? round((threeR_op * 100) / threeT_op) . '%' : '0%',
                lr_op,
                lt_op,
                lt_op > 0 ? round((lr_op * 100) / lt_op) . '%' : '0%',
                ro_op,
                rd_op,
                rt_op,
                ct_op,
                cs_op,
                pd_op,
                in_op,
                bp_op,
                fte_op,
                fpr_op,
                eval_op,                // Stats
TM POSS              $poss,
DTM POSS             $poss_op,
Off Rtg               $poss > 0 ? round(100 * $pointEquipe / $poss, 1) : 0,
Def Rtg                $poss_op > 0 ? round(100 * $pointEquipeOpp / $poss_op, 1) : 0,
NetRtg                ($poss > 0 ? round(100 * $pointEquipe / $poss, 1) : 0) - ($poss_op > 0 ? round(100 * $pointEquipeOpp / $poss_op, 1) : 0),
%eFG                (twoT + threeT) > 0 ? round((((twoR + threeR)+0.5*threeR)/(twoT + threeT)) * 100) . '%' : 0,
<!-- %OREB                (ro+rd_op) > 0 ? round((ro/(ro+rd_op))*100) . '%' : 0, -->
%TOV                $poss > 0 ? round((in/$poss)*100) . '%' : 0,
FT_Rate                (twoT + threeT) > 0 ? round(lt/(twoT + threeT),2) : 0,
Opp %eFG                (twoT_op + threeT_op) > 0 ? round((((twoR_op + threeR_op)+0.5*threeR_op)/(twoT_op + threeT_op))*100) . '%' : 0,
<!-- Opp $OREB                (ro_op+rd) > 0 ? round(( ro_op/(ro_op+rd))*100) . '%' : 0, -->
Opp %TOV                $poss_op > 0 ? round((in_op/$poss_op)*100) . '%' : 0,
Opp FT_Rate                twoT_op > 0 ? round(lt_op / twoT_op + threeT_op,2) : 0,
%Floor                $poss > 0 ? round(($ScPoss/$poss)*100) . '%' : 0,
%Stop                $poss_op > 0 ? round((($poss_op-$ScPoss_op)/$poss_op)*100) . '%' : 0,
%AST                $poss > 0 ? round((pd/$poss)*100) . '%' : 0,
%STL                $poss_op > 0 ? round((in/$poss_op)*100) . '%' : 0,
%BLK                twoT_op > 0 ? round((ct_op/twoT_op)*100) . '%' : 0,
%Opp AST                $poss_op > 0 ? round((pd_op/$poss_op)*100) . '%' : 0,
%Opp STL                $poss > 0 ? round((in_op/$poss)*100) . '%' : 0,
%Opp BLK                twoT > 0 ? round((ct_op/twoT)*100) . '%' : 0,
<!-- %DREB               (rd+ro_op) > 0 ? round((rd/(rd+ro_op))*100) . '%' : 0, -->
<!-- %TREB                (rt+rt_op) > 0 ? round((rt/(rt+rt_op))*100) . '%' : 0, -->
                (twoT_op + threeT_op) > 0 ? round(((twoR_op + threeR_op)/(twoT_op + threeT_op))*100) . '%' : 0,
                twoT_op > 0 ? round((twoR_op/twoT_op)*100) . '%' : 0,
                threeT_op > 0 ? round((threeR_op/threeT_op)*100) . '%' : 0,
                (twoT + threeT) > 0 ? round((twoT/(twoT + threeT))*100) . '%' : 0,
                (twoT + threeT) > 0 ? round((threeT/(twoT + threeT))*100) . '%' : 0,
                (twoT_op + threeT_op) > 0 ? round((twoT_op/(twoT_op + threeT_op))*100) . '%' : 0,
                (twoT_op + threeT_op) > 0 ? round((threeT_op/(twoT_op + threeT_op))*100) . '%' : 0,
                round(((((twoT + threeT) > 0 ? ((twoR + threeR) / (twoT + threeT)) : 0) - ((twoT_op + threeT_op) > 0 ? ((twoR_op + threeR_op) / (twoT_op + threeT_op)) : 0) )*5+0.5)*100) . '%'